---
title: "Set up MTurk survey"
output: html_notebook
---

# Connect to MTurk API

# Create qualifications and qualification requirement

```{r}
# create QualificationType to prevent duplicate responses
qual <- CreateQualificationType(name="Covid: Already completed HIT",
                                description="Already completed identical HIT before.",
                                status = "Active")

# Set up standard qualifications
quals <- list(
  list( #Number of HITs
    QualificationTypeId = "00000000000000000040", Comparator = "GreaterThan", IntegerValues = 100, RequiredToPreview = TRUE
  ), list( #Country
    QualificationTypeId = "00000000000000000071", Comparator = "EqualTo", LocaleValues = list(Country = "US"), RequiredToPreview = TRUE 
  ), list( #Percent Approved
    QualificationTypeId = "000000000000000000L0", Comparator = "GreaterThan", IntegerValues = 90, RequiredToPreview = TRUE
  ))

# Add extra qualification - duplicate marker and individual blacklist

quals <- c(quals, 
    list(  #Extra qualification - not yet participated
    QualificationTypeId = "3A9997MDAVHXT6C4F0BNWYYVD4R0Z1", Comparator = "DoesNotExist", RequiredToPreview = TRUE
  )#,list(  #Extra qualification - not blocked
  #  QualificationTypeId = "3Z51ZTGR644Q1WDP87483T7ZE95WZY", #Comparator = "DoesNotExist", RequiredToPreview = TRUE
#  )
)

qreg <- GenerateQualificationRequirement(quals)

```

# Create HITType and question

```{r}
RegisterHITType(title="Survey on life during the coronavirus pandemic",
                description=
                  "Complete a 10-12-minute academic research survey about your life during the coronavirus pandemic",
                reward="1.25",
                duration=seconds(hours=1), auto.approval.delay = seconds(days=4),
                keywords="survey, questionnaire, research",
                qual.req = qreq)

temp <- system.file("templates/surveylink2.xml", package = "pyMTurkR")
HIT_vars <- data.frame(TITLE = "Survey on social attitudes (UP residents only!)",
                       LINK = "https://goldpsych.eu.qualtrics.com/jfe/form/SV_bqQtLZItuF64lTv")

hits <- GenerateHITsFromTemplate(template = temp, input = HIT_vars)

CreateHIT(question = GenerateHTMLQuestion(hits[[1]]), hit.type = "35I9CFS6VLI1WRW6FIHBL3ZOU7M5IX", 
          expiration = seconds(hours = 24),
          assignments = 9) 

```

```{r}
temp <- system.file("templates/surveylink3.xml", package = "pyMTurkR")
HIT_vars <- data.frame(Title = "Survey on social attitudes (UP residents only!)",
                       Description = "...",
                       Link = "https://goldpsych.eu.qualtrics.com/jfe/form/SV_bqQtLZItuF64lTv",
                       Code_validation = "x >= 100000 && x <= 999999")

hits <- GenerateHITsFromTemplate(template = temp, input = HIT_vars)

```

